PROMPT Creating Table 'STAFF'
CREATE TABLE STAFF
 (ID   INTEGER NOT NULL
 ,NINO   VARCHAR2(10) NOT NULL
 ,FIRSTNAME VARCHAR2(30) NOT NULL
 ,LASTNAME VARCHAR2(30) NOT NULL
 ,E_MAIL_ADDRESS VARCHAR2(60) NOT NULL )
/

PROMPT Creating Primary Key on 'STAFF'
ALTER TABLE STAFF
 ADD (CONSTRAINT STAFF_PK PRIMARY KEY 
  (ID))
  
/

PROMPT Creating Unique Key on 'STAFF'
ALTER TABLE STAFF
ADD (CONSTRAINT STAFF_UK UNIQUE
    (NINO))
/

grant select on STAFF   to uniprj_tpl;

PROMPT Creating Table 'MODULES'
CREATE TABLE MODULES
 (ID INTEGER NOT NULL
 ,TITLE VARCHAR2(30) NOT NULL
 ,academic_year VARCHAR2(8) NOT NULL
 ,STF_ID_LEADER INTEGER  NULL
 )
/

PROMPT Creating Primary Key on 'MODULES'
ALTER TABLE MODULES
 ADD (CONSTRAINT MODULES_PK PRIMARY KEY 
  (ID))
/

PROMPT Creating Unique Key on 'MODULES'
ALTER TABLE MODULES
ADD (CONSTRAINT MODULES_UK UNIQUE
    (TITLE))
/


PROMPT Creating Foreign Key on 'MODULES'
ALTER TABLE MODULES ADD (CONSTRAINT
 FK_STAFFMODULES FOREIGN KEY 
  (STF_ID_LEADER) REFERENCES STAFF
  (ID))

grant select on MODULES    to uniprj_tpl;


PROMPT Creating Table 'ALLOCATIONS'
CREATE TABLE ALLOCATIONS
 (STF_ID  INTEGER NOT NULL
 ,MDL_ID   INTEGER NOT NULL
 ,ALLOCATED_HOURS INTEGER NOT NULL
 ,SEMESTER INTEGER NOT NULL
 )
/

PROMPT Creating Primary Key on 'ALLOCATIONS'
ALTER TABLE ALLOCATIONS
 ADD (CONSTRAINT ALLOCATIONS_PK PRIMARY KEY 
  (STF_ID, MDL_ID));


PROMPT Creating Foreign Key on 'ALLOCATIONS'
ALTER TABLE ALLOCATIONS ADD (CONSTRAINT
 FK_STAFFALLOCATIONS FOREIGN KEY 
  (STF_ID) REFERENCES STAFF
  (ID))

PROMPT Creating Foreign Key on 'ALLOCATIONS'
ALTER TABLE ALLOCATIONS ADD (CONSTRAINT
 FK_MODULESALLOCATIONS FOREIGN KEY 
  (MDL_ID) REFERENCES MODULES
  (ID))

grant select on ALLOCATIONS   to uniprj_tpl;

select * from staff



